import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import NavBar from "@/components/custom/NavBar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <head>
        {/* Meta tags or links to external CSS */}
      </head>
      <body className={`min-h-screen ${inter.className}`}>
        <NavBar />
        <main className="flex flex-1 justify-center items-center w-full">
          {children}
        </main>
      </body>
    </html>
  );
}
